title: My Awesome Blog
description: Welcome to my new blog hosted on GitHub Pages
theme: jekyll-theme-primer # Optional: you can remove this to use custom CSS completely, but it's a good fallback
url: "" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
markdown: kramdown
permalink: /:year/:month/:day/:title/
